server {
    root /usr/share/nginx/html;
    index index.html;

    set $csp "default-src 'self' 'unsafe-inline'; ";
    set $csp "${csp}script-src 'self' 'unsafe-inline' https://js.stripe.com; ";
    set $csp "${csp}frame-src https://js.stripe.com; ";
    set $csp "${csp}worker-src https://js.stripe.com; ";
    set $csp "${csp}connect-src 'self' http://localhost:8000;";
    add_header Content-Security-Policy $csp always;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
}