server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    add_header Content-Security-Policy "
        default-src 'self'; 
        script-src 'self' https://js.stripe.com; 
        style-src 'self';
        connect-src 'self' http://localhost:8000; 
        frame-src https://js.stripe.com;
        frame-ancestors 'none';
    " always;
}